- alias: Lights - Minimum Brightness 
  id: '999999999001'
  mode: single
  trigger_variables:
    threshold: 50
  trigger: 
  - platform: template
    value_template: >
      {{ expand('group.light_min_brightness')
        | selectattr('state', 'eq', 'on')
        | selectattr('attributes.brightness', 'lt', threshold)
        | map(attribute='entity_id') | list | count }}
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: >
        {% set lights = expand('group.light_min_brightness')
          | selectattr('state', 'eq', 'on')
          | selectattr('attributes.brightness', 'lt', threshold)
          | map(attribute='entity_id') | join(', ') %}
        {{ lights if lights|length > 0 else 'none' }}
    data:
      brightness: "{{ threshold }}"
